<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MT-PF1D0VXM" failures="1" tests="10" name="com.runner.Runner" time="139.912" errors="0" timestamp="2022-07-30T10:19:59 GMT-08:00" skipped="0">
  <testcase classname="com.runner.Runner" name="ValidLogin" time="14.879"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="InValidLogin" time="15.270"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="ShopProductsFunctionality" time="11.634"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="PandG" time="18.897"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="ValidSignup" time="14.543"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="Search" time="13.069"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="Bounce" time="16.670"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="InValidSignup" time="13.173"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="WhatsnewFunctionality" time="10.333"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="BBB" time="11.444">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.runner.Runner.BBB(Runner.java:173)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- BBB -->
  <system-out/>
</testsuite> <!-- com.runner.Runner -->
